name: Tutorial
version: '${project.version}'
main: dev.bence.tutorial.Tutorial
api-version: 1.18

commands:
  heal:
    description: Speler wordt geheald.
  geef:
    description: Geef commando
  kit:
    description: geef kit jezelf
  menu:
    description: opent een gui
  stats:
    description: hier kun jij je stats ziene
  vlieg:
    description: zet vliegen aan of uit
  gamemodes:
    description: Switch gamemode
  selector:
    description: selector
  setjoinmessage:
    description: zet het welkoms bericht
  reload:
    description: reload de plugin
  punish:
    description: lol
